<?php

declare(strict_types=1);

namespace HumanMade\SchemaOrgValidator\Generator;

use RuntimeException;

/**
 * Turns the schema.org JSON-LD dump into the array stored in data/vocabulary.php.
 */
final class VocabularyGenerator
{
    private const PENDING_IRI = 'https://pending.schema.org';

    /** @var array<string, array<string, mixed>> */
    private array $nodes = [];

    /**
     * Builds the vocabulary array from a decoded schemaorg-current-https.jsonld document.
     *
     * @param array<string, mixed> $jsonld
     * @return array<string, mixed>
     */
    public function build(array $jsonld, string $version): array
    {
        $graph = $jsonld['@graph'] ?? null;
        if (!is_array($graph)) {
            throw new RuntimeException('The JSON-LD document has no @graph.');
        }

        $this->nodes = [];
        foreach ($graph as $node) {
            if (is_array($node) && isset($node['@id']) && is_string($node['@id'])) {
                $name = $this->localName($node['@id']);
                if ($name !== null) {
                    $this->nodes[$name] = $node;
                }
            }
        }

        $classes = [];
        $properties = [];
        $members = [];
        foreach ($this->nodes as $name => $node) {
            $nodeTypes = $this->rawTypes($node);
            if (in_array('rdfs:Class', $nodeTypes, true)) {
                $classes[$name] = $node;
            } elseif (in_array('rdf:Property', $nodeTypes, true)) {
                $properties[$name] = $node;
            } else {
                $members[$name] = $nodeTypes;
            }
        }

        $parents = [];
        foreach ($classes as $name => $node) {
            $parents[$name] = $this->localNames($node['rdfs:subClassOf'] ?? null, $classes);
        }

        $dataTypes = $this->dataTypes($classes, $parents);
        $enumerationTypes = $this->descendants('Enumeration', $parents);

        $enumerations = [];
        foreach ($enumerationTypes as $type) {
            $enumerations[$type] = [];
        }
        foreach ($members as $member => $nodeTypes) {
            foreach ($nodeTypes as $nodeType) {
                $type = $this->localName($nodeType);
                if ($type !== null && isset($enumerations[$type])) {
                    $enumerations[$type][] = $member;
                }
            }
        }

        $declared = [];
        $propertyData = [];
        foreach ($properties as $name => $node) {
            $domains = $this->localNames($node['schema:domainIncludes'] ?? null, $classes);
            $ranges = $this->localNames($node['schema:rangeIncludes'] ?? null, $classes);
            foreach ($domains as $domain) {
                $declared[$domain][] = $name;
            }
            $propertyData[$name] = [
                'domains' => $domains,
                'ranges' => $ranges,
                'pending' => $this->isPending($node),
                'supersededBy' => $this->localNames($node['schema:supersededBy'] ?? null, $classes + $properties),
            ];
        }

        $typeData = [];
        foreach ($classes as $name => $node) {
            $typeData[$name] = [
                'parents' => $parents[$name],
                'properties' => $this->sorted($declared[$name] ?? []),
                'pending' => $this->isPending($node),
                'supersededBy' => $this->localNames($node['schema:supersededBy'] ?? null, $classes + $properties),
            ];
        }

        foreach ($enumerations as $type => $names) {
            $enumerations[$type] = $this->sorted($names);
        }

        ksort($typeData, SORT_STRING);
        ksort($propertyData, SORT_STRING);
        ksort($enumerations, SORT_STRING);

        return [
            'version' => $version,
            'types' => $typeData,
            'properties' => $propertyData,
            'dataTypes' => $this->sorted($dataTypes),
            'enumerations' => $enumerations,
        ];
    }

    /**
     * Renders the vocabulary array as deterministic PHP source.
     *
     * @param array<string, mixed> $data
     */
    public function export(array $data): string
    {
        $out = "<?php\n\n// Generated by bin/generate-vocabulary from schema.org. Do not edit.\n"
            . "// See data/LICENSE for the licence of this data.\n\nreturn [\n";
        foreach ($data as $key => $value) {
            if (!is_array($value)) {
                $out .= '    ' . var_export($key, true) . ' => ' . var_export($value, true) . ",\n";
                continue;
            }
            $out .= '    ' . var_export($key, true) . " => [\n";
            if ($this->isList($value)) {
                foreach ($value as $item) {
                    $out .= '        ' . var_export($item, true) . ",\n";
                }
            } else {
                foreach ($value as $name => $entry) {
                    $out .= '        ' . var_export((string) $name, true) . ' => ' . $this->inline($entry) . ",\n";
                }
            }
            $out .= "    ],\n";
        }

        return $out . "];\n";
    }

    /**
     * Returns the schema.org version number published as latest.
     */
    public function latestVersion(): string
    {
        $url = 'https://raw.githubusercontent.com/schemaorg/schemaorg/main/versions.json';
        $json = json_decode($this->fetch($url), true);
        if (is_array($json) && isset($json['schemaversion']) && is_string($json['schemaversion'])) {
            return $json['schemaversion'];
        }

        throw new RuntimeException('Could not work out the latest schema.org version.');
    }

    /**
     * Downloads a URL with cURL or the stream wrappers.
     */
    public function fetch(string $url): string
    {
        $body = false;
        if (function_exists('curl_init')) {
            $curl = curl_init($url);
            if ($curl !== false) {
                curl_setopt_array($curl, [
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_FOLLOWLOCATION => true,
                    CURLOPT_FAILONERROR => true,
                    CURLOPT_TIMEOUT => 120,
                ]);
                $body = curl_exec($curl);
            }
        } else {
            $body = @file_get_contents($url);
        }

        if (!is_string($body) || $body === '') {
            throw new RuntimeException("Could not download {$url}.");
        }

        return $body;
    }

    /**
     * @param mixed $value
     */
    private function inline($value): string
    {
        if (!is_array($value)) {
            return var_export($value, true);
        }

        $parts = [];
        $isList = $this->isList($value);
        foreach ($value as $key => $item) {
            $parts[] = ($isList ? '' : var_export($key, true) . ' => ') . $this->inline($item);
        }

        return '[' . implode(', ', $parts) . ']';
    }

    /**
     * @param array<mixed> $value
     */
    private function isList(array $value): bool
    {
        return $value === [] || array_keys($value) === range(0, count($value) - 1);
    }

    /**
     * @param array<string, mixed> $node
     * @return list<string>
     */
    private function rawTypes(array $node): array
    {
        $type = $node['@type'] ?? [];

        return array_values(array_filter(is_array($type) ? $type : [$type], 'is_string'));
    }

    private function localName(string $id): ?string
    {
        foreach (['schema:', 'https://schema.org/', 'http://schema.org/'] as $prefix) {
            if (strpos($id, $prefix) === 0) {
                $name = substr($id, strlen($prefix));

                return $name === '' ? null : $name;
            }
        }

        return null;
    }

    /**
     * Local names of the schema.org terms in a JSON-LD reference or list of references.
     *
     * @param mixed $value
     * @param array<string, mixed> $known
     * @return list<string>
     */
    private function localNames($value, array $known): array
    {
        if (!is_array($value)) {
            return [];
        }
        if (isset($value['@id'])) {
            $value = [$value];
        }

        $names = [];
        foreach ($value as $reference) {
            if (is_array($reference) && isset($reference['@id']) && is_string($reference['@id'])) {
                $name = $this->localName($reference['@id']);
                if ($name !== null && isset($known[$name])) {
                    $names[] = $name;
                }
            }
        }

        return $this->sorted($names);
    }

    /**
     * @param array<string, mixed> $node
     */
    private function isPending(array $node): bool
    {
        $value = $node['schema:isPartOf'] ?? null;
        if (!is_array($value)) {
            return false;
        }
        if (isset($value['@id'])) {
            $value = [$value];
        }
        foreach ($value as $part) {
            if (is_array($part) && ($part['@id'] ?? null) === self::PENDING_IRI) {
                return true;
            }
        }

        return false;
    }

    /**
     * Classes typed as schema:DataType plus every class descending from them.
     *
     * @param array<string, array<string, mixed>> $classes
     * @param array<string, list<string>> $parents
     * @return list<string>
     */
    private function dataTypes(array $classes, array $parents): array
    {
        $result = [];
        foreach ($classes as $name => $node) {
            if (in_array('schema:DataType', $this->rawTypes($node), true)) {
                $result[$name] = true;
                foreach ($this->descendants($name, $parents) as $descendant) {
                    $result[$descendant] = true;
                }
            }
        }

        return array_keys($result);
    }

    /**
     * @param array<string, list<string>> $parents
     * @return list<string>
     */
    private function descendants(string $root, array $parents): array
    {
        $found = [];
        $changed = true;
        while ($changed) {
            $changed = false;
            foreach ($parents as $name => $list) {
                if (isset($found[$name])) {
                    continue;
                }
                foreach ($list as $parent) {
                    if ($parent === $root || isset($found[$parent])) {
                        $found[$name] = true;
                        $changed = true;
                        break;
                    }
                }
            }
        }

        return array_keys($found);
    }

    /**
     * @param array<int, string> $values
     * @return list<string>
     */
    private function sorted(array $values): array
    {
        $values = array_values(array_unique($values));
        sort($values, SORT_STRING);

        return $values;
    }
}
